[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_presale = "CHKqP8wim3BczkSrsqh6ZKThLYTbEGA5nxDnEbXuZGwB"

[programs.devnet]
token_presale = "CHKqP8wim3BczkSrsqh6ZKThLYTbEGA5nxDnEbXuZGwB"

[programs.mainnet]
token_presale = "CHKqP8wim3BczkSrsqh6ZKThLYTbEGA5nxDnEbXuZGwB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
