[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_presale = "4CQZJe4QcTZf55zywDDp6VFyTYo2dnJJLBDw2zrFv4LU"

[programs.devnet]
token_presale = "4CQZJe4QcTZf55zywDDp6VFyTYo2dnJJLBDw2zrFv4LU"

[programs.mainnet]
token_presale = "4CQZJe4QcTZf55zywDDp6VFyTYo2dnJJLBDw2zrFv4LU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
